In [28]:
import pandas as pd
import numpy as np

from sklearn.cross_validation import cross_val_score
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn import cross_validation
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import metrics
from sklearn import tree

%matplotlib inline

In [20]:
df = pd.read_csv('2014data.csv')
data = df.copy()

In [21]:
question_list = data.columns[3:53]
meta_list = data.columns[53:54].append(data.columns[56:])

data['学历'] = data['学历'].replace({'初中及以下': '0','高中': '1','大学': '2','研究生及以上': '3'})
data['性别'] = data['性别'].replace({'M': '1','F': '0'})
for x in question_list:
    data[x] = data[x].replace({'强烈反对': '0','反对': '0','同意': '1','强烈同意': '1'})
    
data = data.dropna()

In [22]:
# data['学历'] = data['学历'].replace({'初中及以下': '1','高中': '2','大学': '3','研究生及以上': '4'})
# data['性别'] = data['性别'].replace({'M': '1','F': '0'})
# for x in question_list:
#     data[x] = data[x].replace({'强烈反对': 0,'反对': 0,'同意': 1,'强烈同意': 1})
# # data['学历'].replace({'大学': '3'})
# # data['学历'].replace({'研究生及以上': '4'})


In [23]:
def measure_performance(X,y,clf, show_accuracy=True, show_classification_report=True, show_confussion_matrix=True):
    y_pred=clf.predict(X)
    if show_accuracy:
        print "Accuracy of Classifier:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),
    if show_confussion_matrix:
        print "Confusion matrix"
        print metrics.confusion_matrix(y,y_pred),"\n"
    if show_classification_report:
        print "Classification report"
        print metrics.classification_report(y,y_pred),"\n"

In [24]:

# features = []
# labels = []
# features = np.asarray(data[question_list])
# print features
# # for x in meta_list:
# #     labels.append(np.asarray(data[x]))
# labels = np.asarray(data[meta_list[2]])
# print labels

In [25]:
# model = RandomForestClassifier()
# model.fit(x_train,y_train)
# measure_performance(x_test,y_test,model)

In [26]:
# RandomForestClassifier()
for i in range(0,len(meta_list)):    
    features = []
    labels = []
    features = np.asarray(data[question_list].dropna())
    labels = np.asarray(data[meta_list[i]].dropna())
    x_train, x_test, y_train, y_test = train_test_split(features,labels,test_size=0.05,train_size=0.95)
    model = RandomForestClassifier()
    model.fit(x_train,y_train)
    print meta_list[i]
    i += 1
    measure_performance(x_test,y_test,model)

性别
Accuracy of Classifier:0.714 Confusion matrix
[[1822 1196]
 [1246 4275]] 

Classification report
             precision    recall  f1-score   support

          0       0.59      0.60      0.60      3018
          1       0.78      0.77      0.78      5521

avg / total       0.72      0.71      0.71      8539


学历
Accuracy of Classifier:0.647 Confusion matrix
[[   4   26  230    7]
 [   6   65  983   21]
 [  18  188 5356  206]
 [   3   37 1293   96]] 

Classification report
             precision    recall  f1-score   support

          0       0.13      0.01      0.03       267
          1       0.21      0.06      0.09      1075
          2       0.68      0.93      0.79      5768
          3       0.29      0.07      0.11      1429

avg / total       0.54      0.65      0.56      8539




In [29]:
# DecisionTreeClassifier()
for i in range(0,len(meta_list)):    
    features = []
    labels = []
    features = np.asarray(data[question_list])
    labels = np.asarray(data[meta_list[i]])
    x_train, x_test, y_train, y_test = train_test_split(features,labels,test_size=0.05,train_size=0.95)
    dt = tree.DecisionTreeClassifier()
    dt = dt.fit(x_train,y_train)
    print meta_list[i]
    i += 1
    measure_performance(x_test,y_test,dt)

性别
Accuracy of Classifier:0.660 Confusion matrix
[[1584 1418]
 [1481 4056]] 

Classification report
             precision    recall  f1-score   support

          0       0.52      0.53      0.52      3002
          1       0.74      0.73      0.74      5537

avg / total       0.66      0.66      0.66      8539


学历
Accuracy of Classifier:0.484 Confusion matrix
[[  18   52  159   44]
 [  54  180  623  170]
 [ 215  885 3638 1064]
 [  47  198  896  296]] 

Classification report
             precision    recall  f1-score   support

          0       0.05      0.07      0.06       273
          1       0.14      0.18      0.15      1027
          2       0.68      0.63      0.65      5802
          3       0.19      0.21      0.20      1437

avg / total       0.51      0.48      0.50      8539




In [ ]:
#logistic regression
titanic['sex_female'] = titanic['sex'].apply(lambda x:1 if x=='female' else 0)
# creating a new column, contains boolean value
dataset = titanic[['survived']].join([pd.get_dummies(titanic['pclass'],prefix="pclass"),titanic.sex_female])
# creating a new data set, which contains boolean values of pclasses and sex_female and survived
#dataset
lm = LogisticRegression()
#drop pclass_1st to avoid dummy variable trap
x = np.asarray(dataset[['pclass_3rd','pclass_2nd','sex_female']])
y = np.asarray(dataset['survived'])
#　you have to drop one variable, sorry! 
lm = lm.fit(x,y)
print lm.score(x,y)
print type(lm)